import Jimp from "jimp";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { getOrCreateUserEconomy } from "./economy.js";
import { getUserRole } from "./permissions.js";
import { getUserDB } from "./db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CACHE_DIR = path.join(__dirname, "..", "storage", "cache");

// Ensure cache directory exists
if (!fs.existsSync(CACHE_DIR)) {
  fs.mkdirSync(CACHE_DIR, { recursive: true });
}

export async function generateDashboardImage(userId, username) {
  // 1. Fetch user data
  const economy = await getOrCreateUserEconomy(userId);
  const role = await getUserRole(userId);
  
  const db = await getUserDB(userId);
  const agentModeRow = await db.get("SELECT val FROM profile_memory WHERE key = 'agent_mode'");
  const chatModeRow = await db.get("SELECT val FROM profile_memory WHERE key = 'chat_mode'");
  
  const agentMode = agentModeRow ? agentModeRow.val.toUpperCase() : "NORMAL";
  const chatMode = chatModeRow ? chatModeRow.val.toUpperCase() : "STREAMING";
  const gold = economy.gold || 0;
  const gems = economy.gems || 0;
  const tokens = economy.tokens || 0;
  
  // 2. Create a basic image (Canvas 800x450)
  const width = 800;
  const height = 450;
  const image = new Jimp(width, height, "#1a1b26"); // Dark theme background

  // 3. Draw a header box
  const headerHeight = 80;
  for(let x = 0; x < width; x++) {
    for(let y = 0; y < headerHeight; y++) {
      image.setPixelColor(Jimp.cssColorToHex("#24283b"), x, y);
    }
  }
  
  // 4. Load fonts
  const fontTitle = await Jimp.loadFont(Jimp.FONT_SANS_64_WHITE);
  const fontLabel = await Jimp.loadFont(Jimp.FONT_SANS_32_WHITE);

  // 5. Print text
  image.print(fontTitle, 20, 10, "ELYNISIA DASHBOARD");
  
  // Line separator
  for(let x = 20; x < width - 20; x++) {
    for(let y = headerHeight + 10; y < headerHeight + 12; y++) {
      image.setPixelColor(Jimp.cssColorToHex("#7aa2f7"), x, y);
    }
  }

  // Draw user stats
  let startY = 120;
  const lineSpacing = 50;
  
  image.print(fontLabel, 40, startY, `USER: @${username || userId}`);
  startY += lineSpacing;
  image.print(fontLabel, 40, startY, `ROLE: ${role.toUpperCase()}`);
  startY += lineSpacing;
  
  image.print(fontLabel, 40, startY, `GOLD: ${gold.toLocaleString()}`);
  startY += lineSpacing;
  image.print(fontLabel, 40, startY, `GEMS: ${gems.toLocaleString()}`);
  startY += lineSpacing;
  image.print(fontLabel, 40, startY, `TOKENS: ${tokens.toLocaleString()}`);
  
  // Draw AI Stats on the right side
  let rightX = 450;
  let rightY = 120;
  
  image.print(fontLabel, rightX, rightY, `AI SETTINGS`);
  rightY += lineSpacing;
  image.print(fontLabel, rightX, rightY, `AGENT: ${agentMode}`);
  rightY += lineSpacing;
  image.print(fontLabel, rightX, rightY, `CHAT:  ${chatMode}`);

  // Draw footer
  image.print(await Jimp.loadFont(Jimp.FONT_SANS_16_WHITE), 20, height - 30, "Generated by Elynisia Core Engine");

  // Save to file
  const outputPath = path.join(CACHE_DIR, `dashboard_${userId}.png`);
  await image.writeAsync(outputPath);
  
  return outputPath;
}
